services:
  postgres:
    container_name: commerce-postgres
    image: pgvector/pgvector:pg17
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-commerce}
      POSTGRES_USER: ${POSTGRES_USER:-commerce}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-commerce}
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./database/postgres/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-commerce}"]
      interval: 5s
      timeout: 5s
      retries: 10

  products:
    build:
      context: .
      dockerfile: services/products/Dockerfile
    container_name: commerce-products
    ports:
      - "8082:8082"
      - "8092:8092"
    environment:
      ACTIVE_PROFILE: d-compose
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy

  orders:
    build:
      context: .
      dockerfile: services/orders/Dockerfile
    container_name: commerce-orders
    ports:
      - "8083:8083"
    environment:
      ACTIVE_PROFILE: d-compose
    restart: unless-stopped
    depends_on:
      - products

  # redis:
  #   image: redis/redis-stack:latest
  #   restart: unless-stopped
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis:/var/lib/redis/data
  #   healthcheck:
  #     test: [ "CMD", "redis-cli", "ping" ]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 10

volumes:
  postgres:
